# -*- coding: utf-8 -*-
"""Red Neuronal Convolucional

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wsrz7mxBpJb2FkliRoMggpTfPdJRlojZ
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt

datos, metadatos = tfds.load("mnist", as_supervised=True, with_info=True)

metadatos

datos_entrenamiento = datos["train"]
datos_pruebas = datos["test"]

nombres_clases = metadatos.features["label"].names

#Normalizaxion
#0-255 byte
#Transformar 0-255 0-1 (0=0, 255=1, 127.5=0.5)

#Normalizar datos entrenamiento y pruebas con una funcion
def normalizar(imagenes, etiquetas):
  imagenes = tf.cast(imagenes, tf.float32)
  imagenes /= 255
  return imagenes, etiquetas

#Normalizar los datos de entrenamiento con la funcion
datos_entrenamiento = datos_entrenamiento.map(normalizar)
datos_pruebas = datos_entrenamiento.map(normalizar)

#Agregar cache
datos_entrenamiento = datos_entrenamiento.cache()
datos_pruebas = datos_pruebas.cache()

for imagen, etiqueta in datos_entrenamiento.take(1):
  break

import matplotlib.pyplot as plt

#Mostrarlo en pantalla
plt.figure()
plt.imshow(imagen, cmap=plt.cm.binary)
plt.colorbar()
plt.show()

plt.figure(figsize=(10,10))
for i, (imagen, etiqueta) in enumerate(datos_entrenamiento.take(25)):
  #Mostrarlo en pantalla
  plt.subplot(5, 5, i+1)
  plt.imshow(imagen, cmap=plt.cm.binary)

plt.show()

"""modelo = tf.keras.Sequential([
    #784 datos de entrada
    tf.keras.layers.Flatten(input_shape=(28,28,1)),
    #Capa oculta
    tf.keras.layers.Dense(50, activation=tf.nn.relu),
    tf.keras.layers.Dense(50, activation=tf.nn.relu),
    #Capa de salida
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)


])"""

modelo = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), input_shape=(28,28,1), activation = "relu"),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Conv2D(64, (3,3), activation = "relu"),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=100, activation="relu"),
    tf.keras.layers.Dense(10, activation="softmax")

])

modelo.compile(
    optimizer="adam",
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=["accuracy"])

TAMANO_LOTE = 32
datos_entrenamiento = datos_entrenamiento.repeat().shuffle(60000).batch(TAMANO_LOTE)
datos_pruebas = datos_pruebas.batch(TAMANO_LOTE)

import math

#Entrenar
entrenamiento = modelo.fit(
    datos_entrenamiento, epochs=10,
    steps_per_epoch=math.ceil(60000/TAMANO_LOTE)

)

datos, metadatos = tfds.load("cats_vs_dogs", as_supervised=True, with_info=True)

metadatos

tfds.show_examples(datos["train"], metadatos)

import matplotlib.pyplot as plt
import cv2 #opencv - trabajar y hacer transformaciones en imagenes

plt.figure(figsize=(20,20))

TAMANO_IMG=100

for i, (imagen, etiqueta) in enumerate(datos["train"].take(25)):
  imagen = cv2.resize(imagen.numpy(), (TAMANO_IMG, TAMANO_IMG))
  imagen = cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)
  plt.subplot(5, 5, i+1)
  plt.imshow(imagen, cmap="gray")

datos_entrenamiento = []

for i, (imagen, etiqueta) in enumerate(datos["train"].take(25)):
  imagen = cv2.resize(imagen.numpy(), (TAMANO_IMG, TAMANO_IMG))
  imagen = cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)
  imagen = imagen.reshape(TAMANO_IMG, TAMANO_IMG, 1)
  datos_entrenamiento.append([imagen, etiqueta])

datos_entrenamiento[0]

#Prepara variables X y y
X = []
y = []

for imagen, etiqueta in datos_entrenamiento:
  X.append(imagen)
  y.append(etiqueta)

#Normalizar las imagenes
import numpy as np

X = np.array(X).astype(float) / 255

X[0]

y

y = np.array(y)

modelo = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3,3), activation="relu", input_shape=(100, 100, 1)),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation="relu"),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(128, (3,3), activation="relu"),
    tf.keras.layers.MaxPooling2D(2,2),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(100, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

modelo.compile(
    optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"]
)

modelo.fit(
    X, y, batch_size=32, validation_split=0.15, epochs=50

)

#Sobreajuste por tener tanto accuracy en entrenamiento pero en pruebas bajo (over-fitting)

#Dropout
#Aumento de datos